name: mlops-ci

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      force_retrain:
        description: "Forzar retraining"
        required: false
        default: "false"

jobs:
  build-train-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Provenance
        run: python scripts/00_provenance.py

      - name: Validate & clean data
        run: python scripts/01_validar_datos.py

      - name: Train baseline
        run: python scripts/02_train_baseline.py

      - name: Upload artifacts (models + processed data)
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            models/
            data/processed/housing_clean.csv
            data/provenance.json

  drift-check:
    needs: build-train-test
    runs-on: ubuntu-latest
    outputs:
      drift: ${{ steps.setout.outputs.drift }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install scipy

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts
          path: .

      - name: Ensure logs dir
        run: mkdir -p logs

      - name: Run drift check
        id: drift
        run: |
          # si no hay logs/predictions.csv, el script saldrá con mensaje pero sin error
          python scripts/04_drift_check.py || true

      - name: Set output
        id: setout
        run: |
          DRIFT=false
          if [ -f logs/drift_report.json ]; then
            python -c "import json; r=json.load(open('logs/drift_report.json')); print('true' if r.get('summary',{}).get('drift_detected') else 'false')" > drift_flag.txt
            DRIFT=$(cat drift_flag.txt)
          fi
          echo "drift=$DRIFT" >> $GITHUB_OUTPUT

  retrain-and-docker:
    needs: [build-train-test, drift-check]
    if: needs.drift-check.outputs.drift == 'true' || github.event.inputs.force_retrain == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install xgboost scipy

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts
          path: .

      - name: Retrain if better
        run: |
          python scripts/03_retrain_if_better.py --force

      - name: Upload updated artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts-updated
          path: |
            models/
            data/processed/housing_clean.csv
            data/provenance.json

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
