name: mlops-ci

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      force_retrain:
        description: "Forzar retraining (true/false)"
        required: false
        default: "false"

jobs:
  # 1) Prepara, valida, entrena y publica artefactos + ejecuta tests
  build-train-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # xgboost y scipy por si los scripts los requieren en esta fase
          pip install xgboost scipy
          # deps de test si usas pytest
          pip install pytest

      - name: Provenance
        run: python scripts/00_provenance.py

      - name: Validate & clean data
        run: python scripts/01_validar_datos.py

      - name: Train baseline
        run: python scripts/02_train_baseline.py

      - name: Unit tests
        run: pytest -q

      - name: Upload artifacts (model + processed data)
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            models/
            data/processed/housing_clean.csv
            data/provenance.json
          if-no-files-found: error

  # 2) Calcula drift si existen logs de predicciones; no falla si no hay logs
  drift-check:
    needs: build-train-test
    runs-on: ubuntu-latest
    outputs:
      drift: ${{ steps.setout.outputs.drift }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install scipy

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts
          path: .

      - name: Ensure logs dir
        run: mkdir -p logs

      - name: Run drift check (tolerant)
        run: |
          # Si no hay logs/predictions.csv, el script puede salir sin error
          python scripts/04_drift_check.py || true

      - name: Set output
        id: setout
        shell: bash
        run: |
          DRIFT=false
          if [ -f logs/drift_report.json ]; then
            python -c "import json; r=json.load(open('logs/drift_report.json')); print('true' if r.get('summary',{}).get('drift_detected') else 'false')" > drift_flag.txt
            DRIFT=$(cat drift_flag.txt)
          fi
          echo "drift=$DRIFT" >> $GITHUB_OUTPUT

  # 3) Retraining solo si hubo drift o si fuerzas por input
  retrain:
    needs: [build-train-test, drift-check]
    if: needs.drift-check.outputs.drift == 'true' || github.event.inputs.force_retrain == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install xgboost scipy

      - name: Download baseline artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts
          path: .

      - name: Retrain if better (does not fail CI)
        run: |
          # Si no mejora, tu script no reemplaza artefactos; en cualquier caso no queremos romper el CI
          python scripts/03_retrain_if_better.py || true

      - name: Upload updated artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts-updated
          path: |
            models/
            data/processed/housing_clean.csv
            data/provenance.json
          if-no-files-found: warn

  # 4) Construye SIEMPRE la imagen cuando build-train-test fue OK
  docker-image:
    needs: [build-train-test, retrain]
    if: needs.build-train-test.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Descarga artefactos "updated" si hubo retraining; si no, se ignora y usaremos los baseline
      - name: Download updated artifacts (if any)
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts-updated
          path: .
        continue-on-error: true

      - name: Download baseline artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts
          path: .
        continue-on-error: true

      - name: Prepare artifacts for build
        shell: bash
        run: |
          # Si existen artefactos "updated", ya están sobre models/ y data/processed/.
          # Si no existen, asegúrate de que los baseline estén presentes.
          if [ ! -f models/best_model.pkl ]; then
            echo "No se encontraron artefactos en models/. Revisar pasos previos."
            ls -la models || true
            exit 1
          fi
          echo "Artefactos que irán al build:"
          ls -la models
          ls -la data/processed || true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute lowercase image name
        id: tag
        shell: bash
        run: |
          IMAGE="ghcr.io/${{ github.repository }}"
          IMAGE_LC=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          echo "image=$IMAGE_LC" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.tag.outputs.image }}:latest
            ${{ steps.tag.outputs.image }}:${{ github.sha }}
